# Generated by Django 5.0.4 on 2024-04-26 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='crashed',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='speed',
        ),
    ]
