# Generated by Django 5.0.4 on 2024-04-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_car_crashed_remove_car_name_remove_car_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='default_name', max_length=100),
        ),
    ]
